feat(ci): test support via plenary test harness
mistweaverco/kulala.nvim pull request #212
Opened 2024-09-02 21:01 UTC by vyskocilm

* add a first test for curl command line parsing.
 * add a GHA workflow file

Inspired by https://github.com/nvim-neotest/neotest/blob/master/.github/workflows/workflow.yaml

2024-09-02 21:08 UTC, vyskocilm commented on .github/workflows/tests.yml
> +            rev: v0.10.0/nvim-linux64.tar.gz
`neotest` does testing on a nightly branch. I don't think this is so interesting, so I removed the nightly branch. The way how `neotest` did this means the cache key is invalidated every day, making cache action less useful.

2024-09-06 06:23 UTC, gorillamoe requested changes

2024-09-06 06:23 UTC, gorillamoe commented on lua/kulala/parser/curl.lua
> +        res.headers[Stringutils.remove_extra_space(header):lower()] = Stringutils.remove_extra_space(value)
I don't think we can do that, because that would be a regression to stuff that @Grueslayer fixed, right?

2024-09-06 06:32 UTC, gorillamoe commented on lua/kulala/parser/curl.lua
> +        res.headers[Stringutils.remove_extra_space(header):lower()] = Stringutils.remove_extra_space(value)
Should be fixed in 6760d2c

2024-09-06 10:52 UTC, gorillamoe submitted a review, later dismissed

2024-09-06 11:26 UTC, gorillamoe approved these changes, later dismissed

2024-09-06 11:29 UTC, gorillamoe submitted a review, later dismissed

2024-09-06 11:36 UTC, gorillamoe submitted a review, later dismissed

2024-09-06 11:51 UTC, gorillamoe approved these changes, later dismissed

2024-09-06 11:53 UTC, gorillamoe submitted a review, later dismissed

2024-09-06 16:26 UTC, gorillamoe submitted a review, later dismissed

2024-09-06 16:37 UTC, gorillamoe submitted a review, later dismissed

2024-09-06 16:40 UTC, treywood approved these changes, later dismissed

2024-09-06 16:40 UTC, gorillamoe approved these changes, later dismissed

2024-09-06 16:55 UTC, gorillamoe submitted a review, later dismissed

2024-09-06 17:03 UTC, gorillamoe submitted a review, later dismissed

2024-09-06 17:19 UTC, gorillamoe approved these changes, later dismissed

2024-09-06 17:59 UTC, merged